const OurTeam = [
  {
    id: 1,
    status: "active",
    data: [
      {
        id: 1,
        ServiceHeader: "All",
        ServiceId: "All",
        ServiceName: "All Zones",
        ServicePara: "",
        Image: "",
        Link: "/",
      },
      {
        id: 2,
        ServiceHeader: "Capt. Ron D’Rozario",
        ServiceName: "Singapore",
        ServiceId: "two",
        ServicePara: "Trainer/Pilot",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 3,
        ServiceHeader: "Capt Mohd Radzi Zain",
        ServiceName: "Malaysia",
        ServiceId: "three",
        ServicePara: "Trainer/Pilot",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },

      {
        id: 4,
        ServiceHeader: "Capt. Ron Rozario",
        ServiceName: "India",
        ServiceId: "four",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 5,
        ServiceHeader: "Capt. Costas Parisidasis",
        ServiceName: "Greece",
        ServiceId: "five",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 6,
        ServiceHeader: "Capt Ralph Rozario ",
        ServiceName: "USA",
        ServiceId: "six",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 7,
        ServiceHeader: `Capt. Abrar <span>(PT Pelindo Astra Maritim, Batam)</span>`,
        ServiceName: "Indonesia",
        ServiceId: "seven",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 8,
        ServiceHeader: "Praveen Thomas",
        ServiceName: "Dubai",
        ServiceId: "eight",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 9,
        ServiceHeader: "Capt. Nalin Peris",
        ServiceName: "Sri Lanka",
        ServiceId: "nine",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 10,
        ServiceHeader: "Capt. Senthil Rengaraju",
        ServiceName: "Singapore",
        ServiceId: "two",
        ServicePara: "Trainer/Pilot",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 11,
        ServiceHeader: "Capt. Firdaus Zainal",
        ServiceName: "Malaysia",
        ServiceId: "three",
        ServicePara: "Auditor",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 12,
        ServiceHeader: "Capt. Gyanendra Singh ",
        ServiceName: "India",
        ServiceId: "four",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 13,
        ServiceHeader: "Alkis Koukos",
        ServiceName: "Greece",
        ServiceId: "five",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 14,
        ServiceHeader: "Capt. Erianto",
        ServiceName: "Indonesia",
        ServiceId: "seven",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 15,
        ServiceHeader: "C/E Ahmed Faz.",
        ServiceName: "Dubai",
        ServiceId: "eight",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 16,
        ServiceHeader: "Capt. Harendra Perera",
        ServiceName: "Sri Lanka",
        ServiceId: "nine",
        ServicePara: "Trainer/Pilot",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 17,
        ServiceHeader: "Capt. Capt Vijay Pal",
        ServiceName: "Singapore",
        ServiceId: "two",
        ServicePara: "Trainer / Auditor",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 18,
        ServiceHeader: "Harry Logasekeran.",
        ServiceName: "Malaysia",
        ServiceId: "three",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 19,
        ServiceHeader: "Capt. Andy Bhasin",
        ServiceName: "India",
        ServiceId: "four",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 20,
        ServiceHeader: " C/E Siva Rajan",
        ServiceName: "Singapore",
        ServiceId: "two",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 21,
        ServiceHeader: "Capt Abadin",
        ServiceName: "Indonesia",
        ServiceId: "seven",
        ServicePara: "Advisor / Pilot",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
      {
        id: 22,
        ServiceHeader: "C/E Robin Bhasin",
        ServiceName: "India",
        ServiceId: "four",
        ServicePara: "",
        Image: "/assets/about-us/our-team/1.webp",
        Link: "/",
      },
    ],
  },
];

export { OurTeam };
