const ContactsList = [
  {
    id: 1,
    status: "active",
    data: [
      {
        id: 1,
        PilotName: "Capt.Ron D’Rozario",
        PilotPhone: "+65 9664 1872",
        Mail: "rozarioronaldo@gmail.com",
        Mail1: "",
        GroupName: "Singapore",
      },
      {
        id: 2,
        PilotName: "Capt. Senthil",
        PilotPhone: "+65 8406 6188",
        Mail: "arkstraitspilot@gmail.com",
        Mail1: "",
        GroupName: "Singapore",
      },
      {
        id: 3,
        PilotName: "Hema",
        PilotPhone: "+65 8656 2140",
        Mail: "arkglobalmanagement@gmail.com",
        Mail1: "",
        GroupName: "Singapore",
      },
      {
        id: 4,
        PilotName: "C/E Rajan",
        PilotPhone: "+65 9639 3642",
        Mail: "",
        Mail1: "",
        GroupName: "Singapore",
      },
      {
        id: 5,
        PilotName: "Capt. Radzi Zain",
        PilotPhone: "+60 1 6275626",
        Mail: "",
        Mail1: "",
        GroupName: "Malaysia",
      },
      {
        id: 6,
        PilotName: "Capt. Senthil",
        PilotPhone: "+60 1 6275626",
        Mail: "",
        Mail1: "",
        GroupName: "Malaysia",
      },
      {
        id: 7,
        PilotName: "Capt. Abrar",
        PilotPhone: "+62 811 6702 403",
        Mail: "",
        Mail1: "",
        GroupName: "Indonesia",
      },
      {
        id: 8,
        PilotName: "Agung Osmond",
        PilotPhone: "+62 778 4890 037",
        Mail: "",
        Mail1: "",
        GroupName: "Indonesia",
      },
      {
        id: 9,
        PilotName: "Capt. Ron",
        PilotPhone: "+91 87543 70434",
        Mail: "",
        Mail1: "",
        GroupName: "India",
      },
      {
        id: 10,
        PilotName: "Capt. Andy",
        PilotPhone: "+91 94423 50411",
        Mail: "",
        Mail1: "",
        GroupName: "India",
      },
      {
        id: 11,
        PilotName: "Capt. Ralph Rozario",
        PilotPhone: "+1 713 560 9565",
        Mail: "rozariorvd@gmail.com",
        Mail1: "rozarioronaldo@gmail.com",
        GroupName: "USA/Canada",
      },
      {
        id: 12,
        PilotName: "Coming Soon",
        PilotPhone: "",
        Mail: "",
        Mail1: "",
        GroupName: "Coming Soon",
      },
    ],
  },
];

export { ContactsList };
